#!/bin/bash 

# This is for the systemctl status for mysql and apache server. 

nginx_service() {

	read -p "Start a webserver? " var
	if [ $var == 'y' ] || [ $var == 'Y' ]
	then
		systemctl start nginx
		systemctl status nginx | grep "running" > /dev/null 2>&1

		if [ $? -eq 0 ]
		then
			echo "Nginx started sccessfully!"
		fi

	else
		exit 0

	fi
}

mysql_service() {
	
	read -p "Start a mysql database? ['y/n'] "  var
	if [ $var == 'y' ] || [ $var == 'Y' ]
	then
		systemctl start mysql 
		systemctl status nginx | grep "running"  > /dev/null 2>&1

		if [ $? -eq 0 ]
		then 
			echo "Mysql started scccessfully!"
		fi
	else
		exit 0
	fi
}

php_service() {
	read -p "Start a php service? ['y/n']" var
	if [ $var == 'y' ] || [ $var == 'Y' ]
	then
		systemctl start php7.2-fpm
		systemctl status php7.2-fpm | grep "running" > /dev/null 2>&1

		if [ $? -eq 0 ]
		then 
			echo "Php started successfully!"
		fi
	else
		exit 0
	fi
}

systemctl status nginx | grep inactive  > /dev/null 2>&1

if [ $? -eq 0 ]
then
	echo "Nginx webserver is not running. "
	nginx_service
else
	echo "webserver is running"
fi

systemctl status mysql | grep inactive > /dev/null 2>&1

if [ $? -eq 0 ] 
then
	echo "Mysql is not running. "
	mysql_service
else
	echo "mysql is running. "
fi

systemctl status php7.2-fpm | grep inactive > /dev/null 2>&1

if [ $? -eq 0 ]
then
	echo "PHP is not running "
	php_service
else
	echo "PHP is running"
fi
