#!/bin/bash
### INSTALL KUBERNETES IN UBUNTU 20.04 LTS

############################################################################
## INSTALLATION REQUIREMENTS                                               
## -------------------------
##
##
## Ubuntu 20.04 LTS
## 2 CPU CORE
## 
############################################################################


# Check the ip address of the system 
# ip -4 addr show wlp1s0 | grep -oP "(?<=inet).*(?=/)"

VAR=$(hostname -I | awk '{print $1}')
echo $VAR
exit

## You need to have root access for running this script. 

if [ $(id -u) != 0 ]
then
    echo "Root Privilage Required!!"
    exit
fi

swapoff -a

apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key add -

cat <<EOF |  tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

cat <<EOF > /etc/sysctl.d/k8.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF

systemctl start docker

systemctl enable docker

systemctl enable kubelet

systemctl start kubelet

hostnamectl set-hostname master-node

echo '$VAR master-node ' >> /etc/hosts

kubeadm init --pod-network-cidr=10.10.0.0/16

wget https://docs.projectcalico.org/v3.11/manifests/calico.yaml
sed -i 's/192.168.0.0\/16/10.10.0.0\/16/g' calico.yaml
kubectl apply -f calico.yaml
rm -rf calico.yaml

mkdir -p ~/.kube
cp -i /etc/kubernetes/admin.conf ~/.kube/admin.conf
chown $(id -u):$(id -u) ~/.kube/admin.conf

echo '.............Kubernetes Setup and Ready to Use...............'

