#!/bin/bash
set -ex

## Install single plane kubernetes cluster in Fedora32

#################################################
##
## INSTALLATION REQUIREMENTS
## Fedora 30+
## 2 core CPU (Compulsory)
##
#################################################

VAR=$(hostname -I | awk '{print $1}')

### Check for the root privilage

if [ $(id -u) -ne 0 ]
then
    echo 
    echo "Root Privilage required"
    echo 
fi

STATE=$(systemctl show -p SubState --value firewalld)

if [ $STATE == "running" ]
then
    systemctl stop firewalld 
    systemctl disable firewalld
fi

# Disable the SELINUX policy

if [ $(getenforce) == "enforcing" ] || [ $(getenforce) == "permissive" ]
then
    setenforce 0 # This is how pirates deals with the selinux  :)
fi

sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config


cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable --now kubelet


cat <<EOF > /etc/sysctl.d/k8.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF

sysctl --system

systemctl start docker

systemctl enable docker

dnf update -y

dnf install -y kubelet kubeadm kubectl

systemctl enable kubelet

systemctl start kubelet

# Add the entries in /etc/hosts
echo $VAR $(hostname) >> /etc/hosts

## Disable the swap memory 
swapoff --all

# Initialize the kubernetes master node with pod network CIDR block
kubeadm init --pod-network-cidr=10.244.0.0/16

mkdir -p ~/.kube
cp -i /etc/kubernetes/admin.conf ~/.kube/config
chown $(id -u):$(id -u) ~/.kube/config

# Control plane node isolation 
kubectl taint node $(hostname) key=value:NoSchedule
kubectl taint nodes --all node-role.kubernetes.io/master-
kubectl taint nodes $(hostname) key:NoSchedule-

## Configure the calico CNI plugins
#kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

# Configure the Kube-Flannel CNI Plugin
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# Get the token for joining the main node with kubeadm 
kubeadm token create --print-join-command


echo '.............Kubernetes Setup and Ready to Use...............'
