#!/bin/bash
set -ex
sudo swapoff -a

sudo kubeadm init --pod-network-cidr=10.10.0.0/16

mkdir -p /home/omega/.kube
sudo cp -i /etc/kubernetes/admin.conf /home/omega/.kube/config
sudo chown -R omega:omega /home/omega/.kube
kubectl taint nodes --all node-role.kubernetes.io/master-

kubectl apply -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

wget https://docs.projectcalico.org/manifests/custom-resources.yaml

sed -i 's/192.168.0.0\/16/10.10.0.0\/16/g' custom-resources.yaml
kubectl apply -f custom-resources.yaml

echo '.............Kubernetes Setup and Ready to Use...............'
