#!/bin/bash

## Install single plane kubernetes cluster in Fedora32

#################################################
## INSTALLATION REQUIREMENTS
## Centos7
## 2 core CPU (Compulsory)
## run from root user
#################################################

STATE=$(systemctl show -p SubState --value firewalld)
echo $STATE

if [ STATE == "running" ]
then
    systemctl stop firewalld 
    systemctl disable firewalld
    echo "inside if "
fi

echo "Success till this point "
exit


echo $STATE
exit
systemctl stop firewalld
systemctl disable firewalld

setenforce 0

sed -i 's/SELINUX=enforcing/SELINUX=disbaled/g' 

sed -i 's/\/dev\/mapper\/centos-swap/#\/dev\/mapper\/centos-swap/g' /etc/fstab
sudo swapoff -a

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

cat <<EOF > /etc/sysctl.d/k8.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF

yum install wget yum-utils device-mapper-persistent-data lvm2 -y
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io -y

systemctl start docker

systemctl enable docker

sudo yum update -y

sudo yum install -y kubelet kubeadm kubectl

systemctl enable kubelet

systemctl start kubelet


#echo '192.168.1.20 node1 worker-node' >> /etc/hosts
kubeadm init --pod-network-cidr=10.10.0.0/16

wget https://docs.projectcalico.org/v3.11/manifests/calico.yaml
sed -i 's/192.168.0.0\/16/10.10.0.0\/16/g' calico.yaml
kubectl apply -f calico.yaml
rm -rf calico.yaml

mkdir -p /root/.kube
sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
sudo chown root:root /root/.kube/config

echo '.............Kubernetes Setup and Ready to Use...............'
