#!/bin/bash

## Install single plane kubernetes cluster in Fedora32

#################################################
##
## INSTALLATION REQUIREMENTS
## Fedora 30+
## 2 core CPU (Compulsory)
##
#################################################

VAR=$(hostname -I | awk '{print $1}')

### Check for the root privilage

if [ $(id -u) -ne 0 ]
then
    echo 
    echo "Root Privilage required"
    echo 
fi

STATE=$(systemctl show -p SubState --value firewalld)

if [ $STATE == "running" ]
then
    systemctl stop firewalld 
    systemctl disable firewalld
fi

# Disable the SELINUX policy

if [ $(getenforce) == "enforcing" ] || [ $(getenforce) == "permissive" ]
then
    setenforce 0 # This is how pirates deals with the selinux  :)
fi

sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config


cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable --now kubelet

## Disable the swap memory 
swapoff --all


cat <<EOF > /etc/sysctl.d/k8.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF

sysctl --system

systemctl start docker

systemctl enable docker

dnf update -y

dnf install -y kubelet kubeadm kubectl

systemctl enable kubelet

systemctl start kubelet

#Enter you desired ip for master
echo $VAR 'pc' >> /etc/hosts

#echo '192.168.1.20 node1 worker-node' >> /etc/hosts
kubeadm init --pod-network-cidr=10.10.0.0/16

kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

mkdir -p ~/.kube
cp -i /etc/kubernetes/admin.conf ~/.kube/admin.conf
chown $(id -u):$(id -u) ~/.kube/admin.conf

# Control plane node isolation 
kubectl taint nodes pc node-role.kubernetes.io/master-


echo '.............Kubernetes Setup and Ready to Use...............'
