#!/bin/bash

OVPN_FILE=$2

usage() {
    echo "Usage: heimdall {import|list|sessions|connect|disconnect}" >&2
    echo
    echo "   import             Import the openvpn config i.e.  heimdall import /path/to/config "
    echo "   list               List all the imported config "
    echo "   sessions           List all the active sessions for the OpenVPN"
    echo "   connect            Connect to the OpenVPN server with user credentials i.e. heimdall connect /path/to/config"
    echo "   disconnect         Disconnect the OpenVPN server i.e. heimdall disconnect"
    echo
    exit 1
}

## Import the OpenVPN User config for importing the User Information
config_import() {
    openvpn3 config-import --config $OVPN_FILE
    exit
}

## List all the imported configs
config_list() {
    openvpn3 configs-list
    exit
}

## List all the active sessions
active_sessions() {
    openvpn3 sessions-list
    exit
}

## Connect to the VPN with the help of existing imported configs
connect_vpn() {

openvpn3 session-start --config $OVPN_FILE
exit
}

## Disconnect from the VPN Network
disconnect_vpn() {
openvpn3 session-manage --session-path $(openvpn3 sessions-list | awk 'NR==2 {print $2}') --disconnect
exit
}

while [[ $# -gt 0 ]];
do
    case $1 in
        -h|--help|help)
            usage;;
        import)
            config_import;;
        list)
            config_list;;
        sessions)
            active_sessions;;
        connect)
            connect_vpn;;
        disconnect)
            disconnect_vpn;;
        *)
            echo "Invalid Option!!"
            exit;;
    esac
done
