#!/bin/python3

import os
import stdiomask
import smtplib, ssl
#
## Mailserver details. 
#port = 587
#smtp_server = "smtp.gmail.com"
#sender_email = "tuxomega1@gmail.com"
#receiver_email = ["omegazyadav1@gmail.com"]
#password = str(stdiomask.getpass("Enter the password:"))


# System Information 

ram_detail=os.popen("free -h | grep Mem | awk '{print $2, $3, $4}'").read().split()
used_ram="Total RAM:"+ram_detail[0]
free_ram="Free RAM:"+ram_detail[1] + '\n'

# Process with maximum RAM and CPU usage. 

processes=os.popen("ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -n15").read()
process_det="Processes holding maximum system resources:\n\n" + processes

# Directory with maximum storage 
ret=os.popen("du -Sh /var | sort -rh | head -15").read()
dir_storage = "\nDirectories with maximum size:\n\n" + ret

# disk utilities

disk_detail=os.popen("df -H / | grep /dev | awk '{print $2, $3, $4, $5}'").read().split()

total_storage="Disk Utilization in the system:\n\nTotol Storage: "+str(disk_detail[0])

disk_used="Used storage: " + str(disk_detail[1])

free_disk="Available storage:" + str(disk_detail[2])

# Threshosd for memory and disk utilization. 

ram_free=os.popen("free -mt | grep Mem | awk '{print $4}'").read()
disk_free=os.popen("df -H / | grep /dev | awk '{print $5}'").read().replace('%','')


message = """
Hi! 

The server is running out of space. 
Here are the details of the processes which are holding 
system memory and resources. 

""" + used_ram + '\n' + free_ram + '\n'+process_det+'\n'+total_storage+'\n'+disk_used+'\n' + free_disk + '\n' + dir_storage
    
print(message)

#context = ssl.create_default_context()
#
#with smtplib.SMTP(smtp_server, port) as server:
#    server.ehlo()  # Can be omitted
#    server.starttls(context=context)
#    server.ehlo()  # Can be omitted
#    server.login(sender_email, password)
#
#    for i in range(len(receiver_email)):
#        if int(ram_free) < 100 or int(disk_free) >=40:
#            server.sendmail(sender_email, receiver_email[i], message)
#        else:
#            print("Resources hasnot crossed the limit. ")
#
